### ISSUE TITLE
Share popover and overlay not respecting device rotation on article views

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-iPad#5]
Sequence:

* When in a single article view, tap on the share buttons at the top or bottom of the article
* The share popover will appear and a slightly opaque overlay will cover the screen
* While the popover/overlay are still engaged, rotate the device
* The popover will not reposition itself properly, and the overlay will retain its original dimensions so that it only covers a portion of the screen

**Comment by bhawk9780** [comment]
Partially fixed in 1.0.7 build 2. The top title bar share drawer is fixed after a rotation, but the bottom button's share drawer refuses to cooperate right now. For the sake of getting 1.0.7 build 2 out, going to table a real fix for that. In 1.0.7 build 2, the bottom share drawer will simply disappear when you rotate.
